<?php

declare(strict_types=1);

namespace Tests\Generated;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;
use Tests\Unit\AddressDiscardExtraItems;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<AddressDiscardExtraItems>
 */
final readonly class AddressDiscardExtraItemsMapper_36be223ea6 extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|AddressDiscardExtraItems
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape([
			'city' => $ts->string(),
			'street' => $ts->string(),
		]);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new AddressDiscardExtraItems(...array_intersect_key($values, ['city' => true, 'street' => true]));
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(AddressDiscardExtraItems::class);
	}
}
