<?php

declare(strict_types=1);

namespace Tests\Generated;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;
use Tests\Unit\Address;
use Tests\Unit\CompileAsObjectType;
use Tests\Unit\Person;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<CompileAsObjectType>
 */
final readonly class CompileAsObjectTypeMapper_634285e0e7 extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|CompileAsObjectType
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape([
			'address' => $ts->object(Address::class),
			'unionBuiltIn' => $ts->union([$ts->object(Address::class), $ts->string()]),
			'union' => $ts->union([$ts->object(Address::class), $ts->object(Person::class)]),
			'nullableAddress' => $ts->optional($ts->nullable($ts->object(Address::class))),
		]);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new CompileAsObjectType(...$values);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(CompileAsObjectType::class);
	}
}
