<?php

declare(strict_types=1);

namespace Tests\Generated;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use RoundingMode;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Conversion\Converter\Bool\LenientBoolConverter;
use Shredio\TypeSchema\Conversion\Converter\Number\LenientNumberConverter;
use Shredio\TypeSchema\Conversion\Converter\String\StrictStringConverter;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;
use Tests\Unit\CustomTypeConverters;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<CustomTypeConverters>
 */
final readonly class CustomTypeConvertersMapper_1662ce3dae extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|CustomTypeConverters
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape([
			'string' => $ts->nullable($ts->string())->conversion(string: new StrictStringConverter()),
			'float' => $ts->float()->conversion(float: new LenientNumberConverter()),
			'int' => $ts->int()->conversion(int: new LenientNumberConverter(0.0, RoundingMode::HalfAwayFromZero)),
			'bool' => $ts->bool()->conversion(bool: new LenientBoolConverter(['yes'], ['no'])),
		]);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		$obj = new CustomTypeConverters();

		// 4. Set properties
		$obj->string = $values['string'];
		$obj->float = $values['float'];
		$obj->int = $values['int'];
		$obj->bool = $values['bool'];

		return $obj;
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(CustomTypeConverters::class);
	}
}
