<?php

declare(strict_types=1);

namespace Tests\Generated;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;
use Tests\Unit\Person;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<Person>
 */
final readonly class PersonMapper_9c00715464 extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|Person
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape([
			'id' => $ts->int(),
			'name' => $ts->string(),
			'address' => new AddressMapper_79b8c3eb3e(),
		]);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		$obj = new Person();

		// 4. Set properties
		$obj->id = $values['id'];
		$obj->name = $values['name'];
		$obj->address = $values['address'];

		return $obj;
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(Person::class);
	}
}
