<?php

declare(strict_types=1);

namespace Tests\Generated;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;
use Tests\Unit\Address;
use Tests\Unit\Person3;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<Person3>
 */
final readonly class Person3Mapper_60dfa3fd56 extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|Person3
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape([
			'id' => $ts->int(),
			'name' => $ts->string(),
			'address' => $ts->mapper(Address::class),
		]);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		$obj = new Person3();

		// 4. Set properties
		$obj->id = $values['id'];
		$obj->name = $values['name'];
		$obj->address = $values['address'];

		return $obj;
	}


	public function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(Person3::class);
	}
}
