<?php

declare(strict_types=1);

namespace Tests\Generated;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;
use Tests\Unit\ReindexObject;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<ReindexObject>
 */
final readonly class ReindexObjectMapper_3deefafaa2 extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|ReindexObject
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape([
			'currency_code' => $ts->string(),
			'earning_assets' => $ts->optional($ts->nullable($ts->float())),
			'good_will' => $ts->nullable($ts->float()),
			'other_assets' => $ts->optional($ts->nullable($ts->float())),
		]);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Reindex values
		$values['currencyCode'] = $values['currency_code'];
		unset($values['currency_code']);

		if (array_key_exists('earning_assets', $values)) {
			$values['earningAssets'] = $values['earning_assets'];
			unset($values['earning_assets']);
		}

		$values['goodWill'] = $values['good_will'];
		unset($values['good_will']);

		if (array_key_exists('other_assets', $values)) {
			$values['otherAssets'] = $values['other_assets'];
			unset($values['other_assets']);
		}

		// 4. Create a new instance
		$obj = new ReindexObject(...array_intersect_key($values, ['currencyCode' => true, 'earningAssets' => true]));

		// 5. Set properties
		$obj->goodWill = $values['goodWill'];

		if (array_key_exists('otherAssets', $values)) {
			$obj->otherAssets = $values['otherAssets'];
		}

		return $obj;
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(ReindexObject::class);
	}
}
