<?php

declare(strict_types=1);

namespace Tests\Generated;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;
use Tests\Unit\ContextFactory;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<ContextFactory>
 */
final readonly class ContextFactoryMapper_6ae243424a extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|ContextFactory
	{
		$context = ContextFactory::createContext($context);

		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(['id' => $ts->int()]);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		$obj = new ContextFactory();

		// 4. Set properties
		$obj->id = $values['id'];

		return $obj;
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(ContextFactory::class);
	}
}
