<?php

declare(strict_types=1);

namespace Tests\Generated;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;
use Tests\Unit\PropertyBefore;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<PropertyBefore>
 */
final readonly class PropertyBeforeMapper_12cb051877 extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|PropertyBefore
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape([
			'value' => $ts->before(PropertyBefore::handleNan(...), $ts->float()),
		]);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		$obj = new PropertyBefore();

		// 4. Set properties
		$obj->value = $values['value'];

		return $obj;
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(PropertyBefore::class);
	}
}
