<?php

declare(strict_types=1);

namespace Tests\Generated;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\Symfony\SymfonyPropertyConstraints;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;
use Tests\Unit\User;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<User>
 */
final readonly class UserMapper_8c5947a17d extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|User
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape([
			'name' => $ts->optional($ts->string()->validate(new SymfonyPropertyConstraints(User::class, 'name'))),
			'age' => $ts->optional($ts->int()->validate(new SymfonyPropertyConstraints(User::class, 'age'))),
		]);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new User(...$values);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(User::class);
	}
}
