<?php declare(strict_types = 1);

namespace Shredio\TypeSchemaCompiler;

use Nette\PhpGenerator\ClassType;
use Nette\PhpGenerator\PhpFile;
use Shredio\TypeSchema\Types\Type;

final readonly class ClassDefinition
{

	public PhpFile $file;
	public ClassType $class;
	public NamespaceResolver $namespaceResolver;
	public string $mappedShortName;

	public function __construct(
		public string $mappedClassName,
		string $targetShortName,
		string $targetNamespace,
	)
	{
		$this->file = (new PhpFile())->setStrictTypes();

		$phpNamespace = $this->file->addNamespace($targetNamespace);
		$this->namespaceResolver = new NamespaceResolver($phpNamespace);
		$this->namespaceResolver->addUse($this->mappedClassName);
		$this->mappedShortName = $this->namespaceResolver->shortName($this->mappedClassName);

		$this->class = $phpNamespace->addClass($targetShortName)
			->setFinal()
			->setReadOnly()
			->addComment('This class was generated by the compiler. Do not modify it manually.')
			->setExtends($this->namespaceResolver->addUse(Type::class));
	}

}
